apiVersion: v1
kind: Pod
metadata:
  name: httpServerPod
spec:
  containers:
    - name: httpServer
      image: registry.cn-hangzhou.aliyuncs.com/connor886/httpserver:1.0.0
      readinessProbe:
        httpGet:
          path: /Healthz
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 2